version: '3'
services:
  db:
    image: postgres
    container_name: db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=test-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
